version: '3.8'
services:
    postgresql:
        image: postgres:latest
        container_name: 'Postgresql-Shared'
        cap_add:
            - SYS_NICE
        restart: always
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: postgresql-env@140
        ports:
            - '5432:5432'
        volumes:
            - ./postgresql-datavolume:/var/lib/postgresql/data
            - ./postgresql-filevolume:/filevolume
